sudo: false
language: ruby
rvm:
  - 2.5
  - 2.4
  - 2.3
env:
  - SUPERBOT_USE_RUBYGEMS=yes
before_install:
  - gem install bundler -v 1.17.1
deploy:
  provider: rubygems
  api_key: ${RUBYGEMS_API_KEY}
  on:
    branch: master
